name: Validate XSOAR Demo

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Run validation script
      run: |
        chmod +x ci-cd/validate_playbook.sh
        ./ci-cd/validate_playbook.sh

    - name: Install coverage
      run: pip install coverage

    - name: Run tests with coverage
      run: |
        export PYTHONPATH=$PYTHONPATH:./scripts
        coverage run -m unittest discover -s scripts/tests -p "test_*.py"
        coverage report -m

    - name: Generate HTML coverage report
      run: |
        coverage html

  #  - name: Upload coverage report as artifact
  #    uses: actions/upload-artifact@v3
  #    with:
  #      name: html-coverage-report
  #      path: htmlcov/
